### ISSUE TITLE
Sort_size-неправильная сортировка в группах и в таблице по размеру

### ISSUE THREAD

**Issue by oblako17** [DikBSD/SharpFBTools#2]
Неправильная сортировка по размеру - сортирует только по первой цифре числа независимо в Mb или  Kb. И в окне Коректора и Дубликатора . (два дополнительных значения после запятой с округлением - супер, для точности оценки - замечена зависимость размера и количество страниц при открытии в читалке). Прилагаю группу файлов "Size" для наглядности. 
https://yadi.sk/d/KhQprqsbiHBaog .  Там посередине есть книга 3.63 Mb, как не нажимай на сортировку в первую строчку она не становится, хотя она - больше всех по размеру.
[Size.zip](https://github.com/DikBSD/SharpFBTools/files/2668393/Size.zip)
![sort_size](https://user-images.githubusercontent.com/45688702/49816876-e5a0e180-fd7f-11e8-9fb0-f2381226d1eb.jpg)

**Comment by DikBSD** [comment]
Исправил. Теперь корректно сортируются и текст, и даты, и размеры файлов.
Скоро залью код на GitHub.

**Comment by DikBSD** [comment]
Залил код в ветку develop.

**Comment by oblako17** [comment]
Скачал...
Оценить изменение не могу, к сожалению, для меня сложно здесь... Я только пытаюсь...
![sharpfbtools-develop](https://user-images.githubusercontent.com/45688702/49888878-2583c980-fe51-11e8-9158-67ec0f9026f1.jpg)

В SourceForge, на радость мне было проще.
Ткните, куда смотреть...
Будет сформирован релиз для чайников, тогда посмотрю. А может и на мыло oblako17@bk.ru
