### ISSUE TITLE
Stop_autocorrection

### ISSUE THREAD

**Issue by oblako17** [DikBSD/SharpFBTools#3]
В окне Корректор при Автокорректировке по списку, натыкаясь на ошибку в структуре определенных файлов, прога останавливается ожидая выхода(прилагаю скрины ошибок и сами файлы с ошибками на которых спотыкается программа). Ошибки в файлах не важны. Хорошо бы не останавливаться, а переходить на следующий по списку файл. Потом разбираться с ошибками.
Ссылка с файлами для тестирования - https://yadi.sk/d/iaJ6FogVK-CLEg. Три файла с ошибками
![2018-12-02_091047](https://user-images.githubusercontent.com/45688702/49814804-6dd0b800-fd7b-11e8-91c4-ec8fe62706c8.jpg)
![2018-12-02_224450](https://user-images.githubusercontent.com/45688702/49814805-6dd0b800-fd7b-11e8-9a68-4881b3765345.jpg)
![2018-12-03_121402](https://user-images.githubusercontent.com/45688702/49814807-6e694e80-fd7b-11e8-8d30-ce84f5977acb.jpg)

**Comment by DikBSD** [comment]
По идее. надо заново переписать fb2 парсер, чтобы он учитывал тот факт, что есть fb2 файлы, основные разделы структуры могут идти не в стандартной последовательности. Но на переписывание парсера требуется много времени и разработка универсального алгоритма.
Посмотрю, что можно пока сделать.

**Comment by DikBSD** [comment]
Улучшена пакетная автокорректировака книг в случае, если встречаются книги, в которых сильно искажена структура, или же основные разделы структуры размещены не по fb2 стандарту.

Если корректируется только одна вышеописанная книга, то генерируется исключение и выдается сообщение о сильно поврежденной структуре файла.

Если запущена пакетная автокорректировка, и встречаются вышеописанные файлы, то они пропускаются, и корректировка переходит к следующему файлу.

Сделан мелкий рефакторинг.
Fix #3

**Comment by oblako17** [comment]
Здравствуйте!
Скажу наперёд, в основном все норм, но во время составления списка выскочило:
![autocorr-02](https://user-images.githubusercontent.com/45688702/49957502-123c3100-ff19-11e8-954f-8e3f781dfb51.jpg)
Нажимаем ОК, дальше продолжает штатно до таблицы на экране. Ошибка появляется не всегда.
Закономерности пока не заметил.
Во время автокорректировки на некоторых, единичных файлах:
![autocorr-01](https://user-images.githubusercontent.com/45688702/49957851-246a9f00-ff1a-11e8-85a7-618ffd2dc00f.jpg)
После нажатия ОК процесс автокорректировки продолжается.
Выяснил. что при повторной автокорректировки, на этом файле уже не застревает, Видимо он меняется, и уже на является объектом ошибки.
Выужу пару таких файлов до автокорректировки, для тестов, вышлю, если не додумаете без отладки.
По поводу ошибки компиляции-сборке сборок. Ларчик открывался просто. В папке Source создаешь папку SharpZipLib и переносишь туда файл ICSharpCode.SharpZipLib.dll.
Собирается и в SharpDevelop и в VS. В VS автоматом создается на диске D(видимо согласно заданию в проекте) папка CSharpDevelopBuild. естественно туда надо перенести указанные вами файлы. При сборке все равно VS с ошибкой укажет на недостающее и пути.
Файлы для теста я вышлю, Если раньше не расколете орешек.
"орешек знания тверд, но мы не привыкли отступать..."
С уважением, oblako!

**Comment by DikBSD** [comment]
Спасибо  за Ваш отзыв.
По поводу 1-го скриншота.
Скорее всего у Вас включена опция "Показывать сообщения об ошибках при
падении работы алгоритмов" в диалоге Настройки. Поэтому Валидатор и выдал
это сообщение. По-видимому, он "упал" на очень большом файле, который не
смог открыть или пропарсить. Такие сообщения полезны для понимания, что
улучшать в программе.
Если Вы эту опцию отключите, то подобные сообщения (а их по программе
сделано множество) не будут больше появляться.

По поводу 2-го скриншота. Буду разбираться. Но из самого скриншота видно,
что падение алгоритма произошло либо на файле 153894.fb2 (он - самый нижний
в списке обработанных файлов), либо - на следующем за ним. Эти файлы бы мне
на "препарирование" :).

С уважением,
Вадим


чт, 13 дек. 2018 г. в 21:24, oblako17 <notifications@github.com>:

**Comment by oblako17** [comment]
Здравствуйте!
По поводу первого Вы правы, был включен Режим отладки в Настройках.
Второй. Высылаю тест-группы(3) файлов.  https://yadi.sk/d/16DfSj3WLc7sGA
Сергей.

**Comment by DikBSD** [comment]
Спасибо.
Нашел, где может быть проблема, но нужны как раз файлы для прогона.
Пока делаю отладочную систему. Она будет вкл/выкл по вышеназванной опции в
Настройках.

С уважением,
Вадим


пт, 14 дек. 2018 г. в 11:58, oblako17 <notifications@github.com>:

**Comment by oblako17** [comment]
Ошибка выскакивает во время создания списка книг с описанием и при выключенной опции "Показывать сообщения об ошибках при падении работы алгоритмов" в диалоге Настройки. Как словить на каких файлах, чтоб понять почему.

**Comment by DikBSD** [comment]
Не могли бы Вы выслать скриншот этой ошибки.

 Я в понедельник буду прогонять алгоритмы на тестах...

**Comment by oblako17** [comment]
Первый скрин. Когда составляется список. Я сперва не поверил. Думал, что не убрал галочку в режиме отладки. Прервал процесс. Оказалось что, галочка убрана. По моему, сообщение то же.
Запустил повторно. Думаю вряд ли там что то другое. Ведь там не определишь файлы на которых срабатывает. Если бы логировать процесс, или в отладке, но отладка прерывается с ошибкой в потоках, Или в тело временно включить пару строк  запись в текст.-файл имя файла на котором сработка, а после +- файл сверху и снизу скопировать для тестирования. А то книг 200000 - долго и расположение только по прогресс бару можно приблизительно определить. Скриншот вышлю, когда проявится.

**Comment by DikBSD** [comment]
Спасибо, я проверю после выходных.
С потоками пока времени нет разобраться. Там много надо чего учитывать.
А так - я как раз и делаю логирование при отладке, когда вычисляют проблемы
:)
Потихоньку разберёмся, в чем там проблема.

**Comment by oblako17** [comment]
Здравствуйте!
Снимаю с повестки последнее свое замечание. Возникновение ошибки в процессе создания списка при выключенной опции "Показывать сообщения об ошибках при падении работы алгоритмов" Видимо я сам глюканул. Наверное ошибка выскочила во время второго этапа создания списка. Я пропустил, когда второй прогресс бар пошел, а прочитать внимательно и скрин сделать не удосужился. Не заморачивайтесь на этом. А вторая ошибка(второй скрин) остаётся актуальной.
С уважением, Сергей.

**Comment by DikBSD** [comment]
Хорошо.  воскресенье, 16 декабря 2018г., 21:51 +03:00 от oblako17  notifications@github.com :
