### ISSUE TITLE
Column order

### ISSUE THREAD

**Issue by oblako17** [DikBSD/SharpFBTools#5]
В таблице - возможность сохранять удобный для пользователя порядок столбцов. Столбцы характеристик, необходимые для сравнения иметь рядом удобней. Для меня удобен порядок - (Название,автор,размер,версия,валидность,путь и т. д.), В VS пытался менять, не получается, а отладка не работает(см. выше). Сейчас при перезагрузке, порядок сбрасывается, снова приходится перекидывать, настраивать ширину...
![column ordert](https://user-images.githubusercontent.com/45688702/49816176-652db100-fd7e-11e8-9296-4d17523fbdce.jpg)

**Comment by DikBSD** [comment]
Сделал.

**Comment by oblako17** [comment]
Здравствуйте!
Уже пробую! С созданием _DebugLogFile.txt лог файла.
Он создается даже при выключенной опции  "Записывать в log файл сообщения об ошибках при падении работы алгоритмов.
А что же будет записывать при включении этой опции? По окончании испытаем.

С уважением, Сергей
L. S.

**Comment by DikBSD** [comment]
Я проверю после выходных, в чем дело.
Не могли бы Вы прислать мне Ваш лог файл - очень интересно
проанализировать, где что падает. В принципе, я делал алгоритмы, чтобы их
падение не сказывалось на результате и обработка продолжалась бы дальше.
Только в сильно битых файлах корректировка прерывается.

**Comment by oblako17** [comment]
Вышлю, не вопрос.
У меня запущено два экземпляра SharpFBTools сейчас. И оба пишут  в лог файл, как я сказал без включенной опции.
Пока идет составления списка. Там в обеих потоках много книг (268 и 208 тысяч). Потом буду запускать автокоррекцию на невалидных. Высылаю дамп лог файла (примерно 25% от полного  ) составления списка.


L. S.

**Comment by oblako17** [comment]
Если выскочит какая-нибудь ошибка, загляну в лог, чтоб узнать на чем остановилась, чтоб потом вам можно было что-нибудь с этим сделать


L. S.

**Comment by DikBSD** [comment]
> У меня запущено два экземпляра SharpFBTools сейчас. И оба пишут  в лог файл, как я сказал без включенной опции.

Мне не удалось это воспроизвести. Возможно, Вы запустили 2 экземпляра SharpFBTools из одной.

**Comment by DikBSD** [comment]
Залил код реализации этой фичи (Column order) на GitHub

**Comment by oblako17** [comment]
Здравствуйте, Вадим!
Видимо да.
После я запускал, создание лог-файла без вкл. опции не обнаружил. Сейчас вторые сутки идет автокорректировка, выскоков нет, лог пишется(опция вкл). По окончании вышлю логи, отдельно создания списка, автокорректировки, затем пропущу автокорректировку на тех файлах, которые не удалось исправить(будут и такие), может понадобятся для анализа. На практике. раньше я их пропускал через Fb2Fix b FBE - они исправлялись

С уважением, Сергей!

L. S.

**Comment by DikBSD** [comment]
> По окончании вышлю логи, отдельно создания списка, автокорректировки, затем пропущу автокорректировку на тех файлах, которые не удалось исправить(будут и такие), может понадобятся для анализа.

Спасибо, будет очень полезно посмотреть на логи...
Как Вы думаете лучше поступить: Сейчас в лог пишется вся информация о падении, независимо от числа запусков программы. Т.е. просто идет добавление к логу. Если 10 раз запустить на каком-то "падучем" файле программу, то 10 раз одно и то же запишется.
Как лучше сделать, чтобы не было дубляжа отладочной информации? Удалять лог при каждом запуске Дубликатора, Корректировщика? И всех инструментов? Или - еще как-то?

**Comment by oblako17** [comment]
А можно добавить Выбор - всегда переписывать лог-файл. Ставишь галочку удаляется старый
лог-файл записывается новый в сессии запуска программы. Если галочка не стоит , то как сейчас с добавлением.


L. S.

**Comment by DikBSD** [comment]
Наверное пока так и сделаю. А там - видно будет...
И еще - надо будет сделать показ лога после завершения обработки (Корректор, Дубликатор, Сортировщик).

**Comment by oblako17** [comment]
Здравствуйте, Вадим!
По поводу Column order. Очень близка к идеалу.
Выставляю: Название-Автор(ы)-Размер-Версия-Валидность-Путь к книге-Жанр(ы) и т. д.
![2018-12-24_233743](https://user-images.githubusercontent.com/45688702/50406423-eac94c00-07d5-11e9-8826-77b8d9601c40.jpg)
После перезагрузки у меня получается: 
Название-Автор(ы)-Размер-Путь к книге-Версия-Валидность-Жанр(ы) и т. д.
т. е. Путь к книге перемещается с 6 на 4 позицию.
![2018-12-24_233823](https://user-images.githubusercontent.com/45688702/50406477-b86c1e80-07d6-11e9-9bcb-7f015b9ba4c9.jpg)
![2018-12-24_233848](https://user-images.githubusercontent.com/45688702/50406481-be61ff80-07d6-11e9-972c-5634a5d7196f.jpg)

**Comment by oblako17** [comment]
Дальше ещё интересней: после следующей перезагрузки -Версия-Валидность- перемещаются за -Жанр(ы)
![2018-12-25_000324](https://user-images.githubusercontent.com/45688702/50406635-477a3600-07d9-11e9-9ba6-595e63e9d4a1.jpg)
 Ёще одна перезагрузка, -Валидность- уходит за -Язык-
![2018-12-25_000454](https://user-images.githubusercontent.com/45688702/50406654-ba83ac80-07d9-11e9-8ffc-68605bd53959.jpg)
![2018-12-25_000514](https://user-images.githubusercontent.com/45688702/50406656-c66f6e80-07d9-11e9-9141-6f4eb6f5c1e3.jpg)
Интересное поведение...
