### ISSUE TITLE
Данные для сравнения

### ISSUE THREAD

**Issue by Sergruz** [DikBSD/SharpFBTools#6]
Здравствуйте! Можно ли реализовать группировку книг по Одинаковые Автор и название книги (уже есть в программе), и при условии одинаковые ID (тоже есть). То есть соединить три условия для группировки.
У меня никак...
для наглядности прилагаю скрины и файлы книг для тестирования
https://yadi.sk/d/K6O37tEPpv0Rbg

![1-OId](https://user-images.githubusercontent.com/53970813/62821570-aaa9b480-bb7f-11e9-9dcf-a6710c0211c5.jpg)
![3-OAN-2](https://user-images.githubusercontent.com/53970813/62821572-b1d0c280-bb7f-11e9-9f24-b8b1dd31f37b.jpg)
![4-ANOId](https://user-images.githubusercontent.com/53970813/62821573-b1d0c280-bb7f-11e9-899c-47903946e00c.jpg)
![2-OAN-1](https://user-images.githubusercontent.com/53970813/62821574-b2695900-bb7f-11e9-9b35-b0e195754eaa.jpg)

**Comment by Sergruz** [comment]
Или на крайняк, поиск групп с одинаковым ID и названием книги...

**Comment by DikBSD** [comment]
Я посмотрю, что можно сделать.

С уважением,
Вадим


пн, 12 авг. 2019 г. в 10:41, Sergruz <notifications@github.com>:

**Comment by Sergruz** [comment]
Попробую объяснить реально сложившуюся ситуацию.
В режиме "одинаковый Id Книги" в числе других обнаруживаются группы:
(Mon Jun 10 20:06:21 2013, Mon Jun 10 20:06:22 2013, Лукьяненко С. В  и Кинг Стивен ) 
С разными книгами. 
Проходить по каждой группе муторно, если их(книг) много. Инструмент "Анализ для всех групп - пометить в каждой группе все "старые" книги (по тэгу version и невалидности)- -удалить " 
сносит лишнее(что стоило бы оставить) - все кроме одной в каждой группе
Первые два можно раскидать по одинаковым автор, название и ID .
Со Стивеном Кингом и Лукьяненко С. В сложнее - автор, название и ID одинаковые, отличие в авторе документов.
Кинг Стивен - Мобильник
Из шести - оставить три(от разных автров fb2 файла, отличаются обложкамиобложками) 
Платов Л. Д. - Архипелаг Исчезающих Островов из трех книг оставить две (от разных аторов fb2 файла, отличаются обложкамиобложками) 
Лукьяненко С. В - Сумеречный дозор. 
Из четырех книг оставить две (от разных авторов fb2 файла, отличаются обложками) 

В режиме "Автор(ы) и Название Книги (одна и та же книга, сделанная разными людьми":
Группа "Твен Марк" имеет  22 книги оставить надо 5, с разными обложками. 
Здесь можно решить также, если раскидать по группам с одинаковыми автор, название и ID .
по поводу группировки с одинаковыми ID и автор документа, наверное это сложнее... 

файлы книг: https://yadi.sk/d/Gl7TvyukOL2SMw

**Comment by DikBSD** [comment]
Я не успел прочитать Ваше последнее письмо - делал алгоритм для
Дубликатора.
Посмотрите, это то, что Вы имели ввиду (тест на присланных вами книгах)?
![1](https://user-images.githubusercontent.com/504339/62869825-39096c00-bd21-11e9-8d10-73df28459862.png)
![2](https://user-images.githubusercontent.com/504339/62869826-39096c00-bd21-11e9-97d3-515ba8c88014.png)
![3](https://user-images.githubusercontent.com/504339/62869827-39096c00-bd21-11e9-9151-27912aa5116f.png)

Если да, то буду делать еще один предложенный вами режим сравнения:
Одинаковый ID книги и Название.

**Comment by DikBSD** [comment]
Если да, то буду делать еще один предложенный вами режим сравнения:
Одинаковый ID книги и Название.

С уважением,
Вадим


пн, 12 авг. 2019 г. в 16:32, Вадим Кузнецов <dikbsd@gmail.com>:

**Comment by Sergruz** [comment]
Да в папке !Box_Compare 47 файлов fb2 для наглядного тестирования. Хотелка - 
min раскидать по группам с одинаковым ID, название и автор книги. 
average - по группам с одинаковым ID и авторам fb2 документа, 
max - Анализ для всех групп - пометить в каждой группе все книги, где   наименьше страниц, оставить одну непомеченным. Если осталось больше одной, пометить "старые". Алгоритм вычисления страниц в книге - не знаю, я использую  AlReader из комплекта MyHomeLib. Там в правом нижнем углу количество страниц.
[AlReader2.Win32.ru.zip](https://github.com/DikBSD/SharpFBTools/files/3492922/AlReader2.Win32.ru.zip)

**Comment by Sergruz** [comment]
Так если получилось Имя, название и ID, я думаю ID и название и ни к чему, лучше попытаться создать ещё группировки с одинаковым ID и авторам fb2 документа
В последних файлах книг для тестирования в группах со Стивеном Кингом, Платов Л. Д, и Лукьяненко С. и имя, и название и ID одинаковые. а книги по обложкам разные и авторам

**Comment by DikBSD** [comment]
Новые пожелания посмотрю позже.
Выложил релиз: код и собранные бинарники на GitHub, SourceForge.net

**Comment by Sergruz** [comment]
группа Лукьяненко разделилась, видимо за счет регистра - при сравнении учитывает и регистр
А в группах с Платовым и Кингом - как разделить...

**Comment by DikBSD** [comment]
Разделила ь и не разделила ь на каком режиме? И, хорошо бы подборку этих книг для теста... 
--
Отправлено из Mail.ru для Android понедельник, 12 августа 2019г., 18:07 +03:00 от Sergruz  notifications@github.com :

**Comment by Sergruz** [comment]
Файлы книг для теста :
https://yadi.sk/d/Gl7TvyukOL2SMw
режим группировки по ID внимание на Лукьяненко 
![01](https://user-images.githubusercontent.com/53970813/62899464-7e995980-bd60-11e9-8975-11310f7a4478.jpg)
режим группировки по автору книги, названию и ID
![02](https://user-images.githubusercontent.com/53970813/62899661-f1a2d000-bd60-11e9-9e5a-30e6ebda091b.jpg)

В названии - дозор и Дозор - буква"д" и "Д", и ID у выбывшей книги в нижнем регистре (строчные буквы)

**Comment by DikBSD** [comment]
Сейчас поправим :)

**Comment by Sergruz** [comment]
Если честно, хотелось бы чтоб разделялись по группам. Потому что у этих книг разные обложки, и авторы документа.
![01](https://user-images.githubusercontent.com/53970813/62921907-ac0ef300-bdb2-11e9-884a-30cbcd53ec66.jpg)
![02](https://user-images.githubusercontent.com/53970813/62921914-b4672e00-bdb2-11e9-8093-1b9a9f03efb8.jpg)

  но не таким способом (регистр)
такие же примеры есть с Кингом, только там регистр одинаковый,(в одной из книг автора документа нет) и по группамм не делится (3 варианта обложки
![04](https://user-images.githubusercontent.com/53970813/62922100-40795580-bdb3-11e9-9bf9-d570c52b4ef1.jpg)
![03](https://user-images.githubusercontent.com/53970813/62922110-44a57300-bdb3-11e9-9058-9129c1e273d0.jpg)
![05](https://user-images.githubusercontent.com/53970813/62922111-466f3680-bdb3-11e9-8e00-7b4b745f90f3.jpg)
И у Платова:
![06](https://user-images.githubusercontent.com/53970813/62922263-aa91fa80-bdb3-11e9-8451-a0058fe39a3b.jpg)
![07](https://user-images.githubusercontent.com/53970813/62922281-b2519f00-bdb3-11e9-971c-3ddbe0269209.jpg)
P. S. автор документа - читать Автор fb2 файла (в таблице внизу справа)

**Comment by DikBSD** [comment]
Выложил на сайты коды и бинарники:

**SharpFBTools-4.47**
**Дубликатор:**
~ Исправлен баг для режимов поиска копий: «5. Автор(ы), Название и Одинаковый Id Книги (разделять по разным группам разные издания книг)» и «6. Название Книги и Id книги (Авторы книги могут быть разными)» (https://github.com/DikBSD/SharpFBTools/issues/6). Теперь в сравнении учитывается и регистр Id Книг.
+ Новая опция: Учитывать Отчество Авторов при сравнении книг. Влияет только на те режимы сравнения, где учитываются Авторы книг.


Все ли теперь хорошо?

**Comment by DikBSD** [comment]
Выложил на сайты коды и бинарники:

**SharpFBTools-4.48**
**Дубликатор:**
~ Исправлено расположение контролов на панели.

**Comment by Sergruz** [comment]
запустил с логом на большом массиве книг, а то вчера  без лога с утра выскочила какая то дрянь.
даже не прочел... что  На будущее надо скрины делать...

**Comment by DikBSD** [comment]
Давайте поступим так.
Пока режимы сделаны без учета автора документа.
Вы погоняйте новый релиз, посмотрите, все ли так, как хочется.
А потом напишите мне, пожалуйста, подробно с картинками (  :-) ), что и как нужно. Я уже путаюсь в потоке информации.
Хорошо?
И - буду благодарен за любые сообщения о багах, скриншоты  и логи.

И еще - включенная опция Учитывать Отчество на режимах для авторов книг (3,4,5) отсеивает много книг, если в книге - несколько авторов с Отчествами.
Будьте внимательны.

**Comment by DikBSD** [comment]
И еще - включенная опция Учитывать Отчество на режимах для авторов книг  (3,4,5) отсеивает много книг, если в книге - несколько авторов с Отчествами.
Будьте внимательны.

**Comment by DikBSD** [comment]
Не утерпел - стал думать над Вашими словами.

Если я верно понял, Вы пишите о том, чтобы Автор fb2 файла учитывался при разбиении на группы ИМЕННО в 1. режиме "1. Одинаковые ID книги"? Или - для других режимов тоже?

**Comment by Sergruz** [comment]
Отвечаю - нет, скорей всего регистр. См посты со скинами с Лукьяненко

**Comment by Sergruz** [comment]
Вдохнуть и выдохнуть (10 раз)!
1. Не понимаю - зачем опция с отчеством. Ведь на примере с Лукьяненко Сергей Васильевич и Лукьяненко Сергей одно и то же лицо. Сомневаюсь, что в одной семье назовут детей одним и тем же именем. Акцент в группировке с книгами не на авторе, а на книге... Считаю опцию лишней, загромождающей код.
2 Конечная цель составлениния групп разделить по группам не только  по автору книги и названию , но и вариантам книг(издание и автор fb2 файла). В данном случае по обложкам. Анализ графически слишком сложно, по моим наблюдениям они различаются по автору fb2 документа. В примере с Лукьяненко(см. посты выше с двумя скинами) они разделились с помощью бага, который Вы поправили. И это правильно - регистр не должен влиять на результат. Ведь в (см. следущий пост после с Лукьяненко)в группах с Кингом и Платовым регистр всех используемых в анализе данных одинаков(верхний - ППРОПИСНЫЕ), а обложки разные. И авторы fb2 файла разные.

Эврика! Пока перебирал пришла шальная мысль - нельзя ли пойти дальше.  создать опцию группировки по Автор(ы), Название, Одинаковый ID и одинаковый Автор fb2 файла! Будет думаю идеально. А там в группах уже анализ.

**Comment by DikBSD** [comment]
> Отвечаю - нет, скорей всего регистр. См посты со скинами с Лукьяненко

Не совсем понял. Регистр уже не учитывается в новом релизе. И Вы писали про Автора fb2 файла, приводя чуть выше скриншоты. Я что-то запутался.

**Comment by Sergruz** [comment]
> Не утерпел - стал думать над Вашими словами.
> 
> Если я верно понял, Вы пишите о том, чтобы Автор fb2 файла учитывался при разбиении на группы ИМЕННО в 1. режиме "1. Одинаковые ID книги"? Или - для других режимов тоже?

В двух:
В 3 - Автор(ы) и Название Книги              + одинаковый Автор fb2 файл
в 5 -  Автор(ы), Название, Одинаковый ID             + одинаковый Автор fb2 файла! 
 Будет думаю идеально. А там в группах уже анализ.

Если заработает 5-й +Автор fb2 файла, то 6 пункт: Название Книги и Id Книги (Авторы книги могут быть разными), возможно будет бессмысленным-лишним.  надо смотреть на практике.
И смех и грех! Кто в лес, кто по дрова. Нашел кнопку цитаты, теперь буду так

**Comment by DikBSD** [comment]
Спасибо, понял. Буду думать над алгоритмом.
По поводу опции Отчества. Надо серьезно подумать, оставить ли ее или удалить. Например, есть 2 писателя Толстой Алексей (Константинович и Николаевич). Опция просто их размежует в разные группы. Правда, она размежует и Лукьяненко Сергея и Лукьяненко Сергея Васильевича в разные группы. Надо подумать, оставить опцию или убрать "от греха подальше"...

**Comment by Sergruz** [comment]
> Спасибо, понял. Буду думать над алгоритмом.
> По поводу опции Отчества. Надо серьезно подумать, оставить ли ее или удалить. Например, есть 2 писателя Толстой Алексей (Константинович и Николаевич). Опция просто их размежует в разные группы. Правда, она размежует и Лукьяненко Сергея и Лукьяненко Сергея Васильевича в разные группы. Надо подумать, оставить опцию или убрать "от греха подальше"...

Насчет Толстых: думаю, с опциями, где включено дополнительно по ID и Автору fb2 файла, они раскидаются по разным группам, а Лукьяненко Сергея и Лукьяненко Сергея Васильевича в одну, если выполнится условия совпадения по ID и Автору fb2 файла... Думаю, лучше отчество и может , даже регистр не учитывать. Все, Лукьяненко Сергей, Лукьяненко Сергея Васильевич
лукьяненко сергей, ЛУКьяненко Сергей Васильевич и др. будут в одной группе если совпадают ID и Автор fb2 файла. Так больше шансов, что это одна и та же книга. А дальше анализ - убрать лишние книги, выбрав наиболее полную и валидную исправлять, если надо ФИО. там другая история

**Comment by DikBSD** [comment]
Хорошо, я уберу опцию Отчества. В крайнем случае, если понадобится - ее не сложно вернуть назад.

**Comment by DikBSD** [comment]
Еще один вопрос: Как Вы думаете, оставить режим 3 и режим 5, и добавить ДВА НОВЫХ, о которых Вы писали. Или же - учет Автора fb2 файла включить в режимы 3, 5, переименовав их?

**Comment by Sergruz** [comment]
> Еще один вопрос: Как Вы думаете, оставить режим 3 и режим 5, и добавить ДВА НОВЫХ, о которых Вы писали. Или же - учет Автора fb2 файла включить в режимы 3, 5, переименовав их?

Думаю 3 оставить,  он нужен иногда.
Добавить ещё один "Автор(ы), Название Книги и Автор fb2 файла", 
а 5 заменить на "Автор(ы), Название, Одинаковый Id Книги и Автор fb2 файла"
или сделать в обоих случаях вкл\откл условия "учитывать Автора fb2 файла" . Что проще и надежнее - выбор за Вами

**Comment by Sergruz** [comment]
Здравствуйте! Обнаружил пары файлов на которых только в новых режимах 5 и 6 выскакивает вот такая бяка. пару высылаю для теста.
![2019-08-14_181627](https://user-images.githubusercontent.com/53970813/63038419-ce476480-bec9-11e9-97bb-c311204cacfb.jpg)
![2019-08-14_181446](https://user-images.githubusercontent.com/53970813/63038422-d0a9be80-bec9-11e9-83e4-02f331910b0e.jpg)
![2019-08-14_181656](https://user-images.githubusercontent.com/53970813/63038426-d2738200-bec9-11e9-98bb-20f08411b05b.jpg)
![2019-08-14_181609](https://user-images.githubusercontent.com/53970813/63038430-d43d4580-bec9-11e9-806d-1e2094215336.jpg)
[файлы.zip](https://github.com/DikBSD/SharpFBTools/files/3502319/default.zip)

**Comment by DikBSD** [comment]
Спасибо, посмотрю. Я забыл доделать для 5 и 6 режимов сохранение в файл и продолжение сравнения из файла. Сейчас делаю...

**Comment by DikBSD** [comment]
Исправил. Выложу, чуть позже, когда доработаю остальные режимы и возобновление сравнения из xml файла.

**Comment by Sergruz** [comment]
> Исправил. Выложу, чуть позже, когда доработаю остальные режимы и возобновление сравнения из xml файла.

?...

**Comment by DikBSD** [comment]
Я доделываю возобновление сравнения из xml для 5 режима. Пока трудности есть. Сам поиск работает, только возобновление пока не работает. 
Могу выложить в GitHub код, как есть. Завтра уже... 
--

**Comment by DikBSD** [comment]
Залил код на GitHub (сюда :) ) в ветку develop:

```
Дубликатор:
~ Исправлено падение Дубликатора для режимов “3. Автор(ы) и Название Книги (одна и та же книга, сделанная разными людьми - разные Id, но Автор и Название - одинаковые)” и “5. Автор(ы), Название и Одинаковый Id Книги (разделять по разным группам разные издания книг)” на файла, где нет тега id к ниги.
+ Алгоритм поиска по Id Книги изменен так, что теперь книги, либо не имеющие тега id Книги, либо тег id есть, но он пустой, группируются в отдельную группу.
~ Проведена оптимизация работы для остальных режимов.
~ Проведен рефакторинг кода.
```
Не работает восстановление сравнения из xml -файла для режима 5.
Надо будет переделывать алгоритм сохранения в файл/восстановления их файла, т.к. он сделан для 2-х условного сравнения книг а тут - 3-х условное. А, когда будут сделаны новые режимы сравнения, учитывающие еще и автора fb2 файла, то условий станет 4.

**Comment by Sergruz** [comment]
Здравствуйте. Если сложности с алгоритмом сохранения в файл/восстановления из файла по более чем 2-х условий, то можно ли хотя бы сделать группировку-сравнение по названию книги и автору документа fb2 файла(2 условия)?

**Comment by DikBSD** [comment]
Да, это несложно.. Я тогда введу эти отдельные режимы, выложу код, а потом полностью переделаю возобновление из файла.

**Comment by DikBSD** [comment]
### SharpFBTools-4.50
**Дубликатор:**
+ Сделан новый режим сравнения: «7. Автор(ы), Название Книги и Автор fb2 файла (одна и та же книга, сделанная разными людьми)».
+ Сделан новый режим сравнения: «8. Автор(ы), Название, Id Книги и Автор fb2 файла».
~ Проведен рефакторинг кода.

Проверьте, пожалуйста, все ли так, корректно работает.

**Comment by Sergruz** [comment]
Я, сейчас отъезжаю. Вечером попробую - скажу!

**Comment by DikBSD** [comment]
Хорошо :)
А я пока буду разрабатывать новый, более универсальный алгоритм работы с прерыванием сравнения.

**Comment by Sergruz** [comment]
> ### SharpFBTools-4.50
> **Дубликатор:**
> 
> * Сделан новый режим сравнения: «7. Автор(ы), Название Книги и Автор fb2 файла (одна и та же книга, сделанная разными людьми)».
> * Сделан новый режим сравнения: «8. Автор(ы), Название, Id Книги и Автор fb2 файла».
>   ~ Проведен рефакторинг кода.
> 
> Проверьте, пожалуйста, все ли так, корректно работает.

Здравствуйте.
Наконец то добрался...
Проверил, Работает, не вылетает, но я был бы счастлив, если бы сотворить режимы 9 и 10 из 8.
 один без Авторы(ы) и другой без Названия или к 6 "Название Книги и Id Книги" прибавить Автор fb2 файла  :
"9. Название, Id Книги и Автор fb2 файла"
«10.. Автор(ы), Id Книги и Автор fb2 файла».
Тандем "Id Книги + Автор fb2 файла" хорошо работает-цепляет дубликаты!
Потом, после тестов, можно убрать за избыточностью лишние режимы

**Comment by DikBSD** [comment]
Хорошо, я сделаю, но, возможно, через неделю
Сейчас на работе просто завал.

**Comment by DikBSD** [comment]
Сергей, я не совсем понял про режим 8. Напишите, пожалуйста, что в нем должно быть конкретно, как Вы это расписали доя 9 и 10 режимов. 
Спасибо. 
--
Отправлено из Mail.ru для Android воскресенье, 01 сентября 2019г., 13:23 +03:00 от Sergruz  notifications@github.com :

**Comment by Sergruz** [comment]
> Сергей, я не совсем понял про режим 8. Напишите, пожалуйста, что в нем должно быть конкретно, как Вы это расписали доя 9 и 10 режимов. Спасибо. >

В восьмом все нормально. Я имел ввиду что в восьмом режиме 4 условия «8. Автор(ы), Название, Id Книги и Автор fb2 файла». из него убрать одно условие "Автор(ы)" останется  3 - "Название, Id Книги и Автор fb2 файла то, что надо.
Тоже самое получится если к 6 "Название Книги и Id Книги" прибавить "Автор fb2 файла"
Не знаю что в коде легче, прибавить условие или отнять.  Но в результате хотелось бы:
"9. Название, Id Книги и Автор fb2 файла"
+
«10.. Автор(ы), Id Книги и Автор fb2 файла».
![Кинг Стив](https://user-images.githubusercontent.com/53970813/64114851-cb3be780-cd96-11e9-907b-6fee3271f438.png)

**Comment by DikBSD** [comment]
Сергей, как лучше оставить: "10. Автор(ы), Id Книги и Автор fb2 файла "
(cм. одноименный скриншот),
или
"10. Id Книги , Автор(ы), и Автор fb2 файла" (см. одноименный скриншот)
?

С уважением,
Вадим

**Comment by Sergruz** [comment]
> Сергей, как лучше оставить: "10. Автор(ы), Id Книги и Автор fb2 файла " (cм. одноименный скриншот), или "10. Id Книги , Автор(ы), и Автор fb2 файла" (см. одноименный скриншот) ? С уважением, Вадим
Здравствуйте! Очень рад...
Если дело в названии - не принципиально, легко поправить.
Если в алгоритме отбора - надо подумать...
Думаю логичнее и понятней  по порядку отбора.
Главное работало бы...

**Comment by DikBSD** [comment]
Там дело в восприятии: что легче воспринимать при анализе копий: Толстой
(545jh5435hfdf34) <Автор fb2> или - 545jh5435hfdf34 (Толстой ) <Автор fb2>
Я сделал итак итак. Какой оставить вариант?

С уважением,
Вадим

**Comment by Sergruz** [comment]
Тогда оставить: "10. Автор(ы), Id Книги и Автор fb2 файла "

**Comment by DikBSD** [comment]
Завтра выложу код и бинарник. Только опять пока не будет работать восстановление поиска из файла до нового алгоритма.

**Comment by DikBSD** [comment]
**SharpFBTools-4.51**
**Дубликатор:**
+ Сделан новый режим сравнения: «9. Название Книги, Id Книги и Автор fb2 файла».
+ Сделан новый режим сравнения: «10. Автор(ы), Id Книги и Автор fb2 файла».
~ Проведен рефакторинг кода.
~ Исправлены мелкие баги

Для новых режимов сравнения не работает сохранение в xml-файл / возобновление сравнения из xml-файла.

**Comment by DikBSD** [comment]
###  **SharpFBTools-4.52**

**Дубликатор:**

    

- Заново переписан алгоритм сохранения прерывания сравнения в файл и возобновления сравнения из файла для Дубликатора. Теперь алгоритм работает для всех режимов сравнения.
-     Сделано отображение пути на диске к выбранному файлу в статус баре для Дубликатора
-     Сделана возможность копировать значение пути к выделенному файлу (статусбара) по клику мышкой на отображении пути в статусбаре для Дубликатора.
-     Изменен метод очищения хеш таблиц для Дубликатора.
-     Исправлены старые серьезные ошибки в коде Дубликатора.
-     Сделан рефакторинг кода Дубликатора.


**Корректор:**   

-  Сделано отображение пути на диске к выбранному файлу в статусбаре для Корректора.
-     Сделана возможность копировать значение пути к выделенному файлу (статусбар) по клику мышкой на отображении пути в статусбаре для Корректора.

**Прежние файла, куда записывались данные при прерывании сравнения Дубликатора не работают!!!**
