### ISSUE TITLE
Дубликатор: Сохранение списка после изменения

### ISSUE THREAD

**Issue by Sergruz** [DikBSD/SharpFBTools#7]
Здравствуйте, Вадим!
Версия 4.52.
После создания списка, открываю его, вношу изменения, Кнопка "Сохранить", выскакивает ошибка:
![2020-01-14_185535](https://user-images.githubusercontent.com/53970813/72361188-1df0bd00-3702-11ea-83d0-b538e59630b4.png)
![2020-01-14_190525](https://user-images.githubusercontent.com/53970813/72361203-22b57100-3702-11ea-9dd3-6e6700a127a6.png)

**Comment by Sergruz** [comment]
Файлы лог и списка
[_DebugLogFile.zip](https://github.com/DikBSD/SharpFBTools/files/4060193/_DebugLogFile.zip)
[001.zip](https://github.com/DikBSD/SharpFBTools/files/4060194/001.zip)

**Comment by Sergruz** [comment]
Заметил: в Сообщении "Не удалось найти часть пути D:\!NewBooksUp\!Out\Горчаков Овидий А"
А файл находится на дике E:\!NewBooksUp\!Out\Горчаков Овидий А
и в списке правильный путь <Path>E:\!NewBooksUp\!Out\Горчаков Овидий А\Горчаков О. А.-Вне закона.fb2</Path>

**Comment by DikBSD** [comment]
Спасибо за сообщение, посмотрю, в чем там дело.

**Comment by DikBSD** [comment]
К сожалению, алгоритм кнопки "Сохранить" перестал работать - она вообще не сохраняет список в открытый файл. Буду разбираться, что к чему.
Пока можно сохранять изменения в списке книг кнопкой "Сохранить группы и файлы". Это менее удобно, т.к. приходиться указывать папку, куда сохранять файл списка, но... За неимением лучшего...

**Comment by DikBSD** [comment]
**SharpFBTools-4.53**

**Дубликатор:**
~ Исправлен баг (Дубликатор: Сохранение списка после изменения https://github.com/DikBSD/SharpFBTools/issues/7). Файл копий списка не сохранялся.

Посмотрите, пожалуйста, все ли теперь у Вас работает? По-идее, проблем больше не должно быть с сохранением Списка копий. Но. кто его знает ... :)
