### ISSUE TITLE
Дубликатор: режим поиска копий книг по Id (№9)

### ISSUE THREAD

**Issue by Sergruz** [DikBSD/SharpFBTools#8]
Делает не то. Наверное неправильно указан обработчик, или перепутаны названия режимов.
В версии 4.53 пункт (№1)все норм.

**Comment by Sergruz** [comment]
> Не работает. Наверное неправильно указан обработчик...
> В версии 4.53 пункт (№1)все норм.
> По практике - его лучше переместить на 3-е место по очереди - пункт №2

**Comment by Sergruz** [comment]
Выяснил методом тыка. Порядок выбора режимов остался как в версии 4,53, изменилось только описание. Поэтому неразбериха. Нажимая пункт "1.Название Книги, Автор(ы), Id Книги и Автор fb2 файла" -  в реальности группируем по старому как в версии 4,53 "1. Одинаковый Id Книги (копии и/или разные версии правки одной и той же книги)", и все остальное

**Comment by DikBSD** [comment]
Спасибо, сейчас посмотрю...

**Comment by DikBSD** [comment]
Починил, спасибо за сообщение о баге. Сейчас выложу исправление.
