### ISSUE TITLE
Дубликатор. Данные для сравнения

### ISSUE THREAD

**Issue by oblako17** [DikBSD/SharpFBTools#9]
Здравствуйте, уважаемый автор! Можете ли Вы добавить ещё один режим для поиска  копий книг:
11 Автор(ы) книги и автор fb2 файла
(т. е. - пункт 2 без "Id Книги")   - для поска дублей когда автор файла или кто нибудь после него, ошибся в названии, иногда в название или присутствует или отсутствует  (СИ) и др., когда после всего изменили ID книги?
Спасибо с уважением , Сергей.

**Comment by DikBSD** [comment]
Хорошо. Но мне нужно несколько подобных файлов для теста. Прикрепите их, пожалуйста.

**Comment by oblako17** [comment]
файлы для тестирования
https://yadi.sk/d/6SPEK0bqewFn-g
[Test_Books_Box.zip](https://github.com/DikBSD/SharpFBTools/files/5358873/Test_Books_Box.zip)

**Comment by DikBSD** [comment]
Спасибо.

**Comment by DikBSD** [comment]
Сделан новый режим сравнения: «11. Автор(ы) и Автор fb2 файла». 

Исходники и бинарные фалы выложены на этом сайте.
